force-app/main/default/objects/Garagem__c/Garagem__c.object-meta.xml
<CustomObject>
    <label>Garagem</label>
    <nameField>
        <label>Nome de Garagem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garagens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Garagem__c/fields/NumeroVagas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVagas__c</fullName>
    <label>Número de Vagas</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Garagem__c.field-meta.xml
<CustomField>
    <fullName>Garagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit de Garagem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>São apenas permitidos produtos do tipo &quot;Vaga&quot;</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vaga</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Garagem__c</referenceTo>
    <relationshipLabel>Vagas</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductHelper.cls
public with sharing class ProductHelper {
    public static void validateLimitOfVagas(List<Product2> produtosDeGaragem) {
        Set<Id> garagemIds = new Set<Id>();
        for(Product2 produto : produtosDeGaragem) {
            if(produto.Garagem__c != null) {
                garagemIds.add(produto.Garagem__c);
            }
        }

        Map<Id, Garagem__c> garagensMap = GaragemDA.getGaragens(garagemIds);

        for(Product2 produto : produtosDeGaragem) {
            if(produto.Garagem__c != null && garagensMap.containsKey(produto.Garagem__c)) {
                Garagem__c garagem = garagensMap.get(produto.Garagem__c);
                Integer qtdVagas = GaragemDA.getQuantityVagasGaragem(produto.Garagem__c);

                if(garagem.NumeroVagas__c <= qtdVagas) {
                    produto.addError('O número de vagas excede o limite permitdo para a garagem');
                }
            }
        }
    }
}