force-app/main/default/objects/Garagem__c/Garagem__c.object-meta.xml
<CustomObject>
    <label>Garagem</label>
    <nameField>
        <label>Nome de Garagem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garagens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Garagem__c/fields/NumeroVagas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVagas__c</fullName>
    <label>Número de Vagas</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Garagem__c.field-meta.xml
<CustomField>
    <fullName>Garagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit de Garagem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>São apenas permitidos produtos do tipo &quot;Vaga&quot;</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vaga</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Garagem__c</referenceTo>
    <relationshipLabel>Vagas</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GaragemDA.cls
public with sharing class GaragemDA {
	public static Map<Id, Garagem__c> getGaragens(Set<Id> garagemIds) {
		if(garagemIds.isEmpty()) return new Map<Id, Garagem__c>();

		return new Map<Id, Garagem__c> (
			[SELECT Id, NumeroVagas__c FROM Garagem__c WHERE Id IN :garagemIds]
		);
	}
	
	public static Integer getQuantityVagasGaragem(Id garagemId) {
        List<AggregateResult> result = [SELECT COUNT(Id) numVagas FROM Product2  WHERE Garagem__c = :garagemId WITH SECURITY_ENFORCED];
		return result[0].get('numVagas') == null ? 0 : Integer.valueOf(result[0].get('numVagas') + '');
	}
}