force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Enterprise__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TemplateController.cls
public with sharing class TemplateController {
    
    @AuraEnabled(cacheable=true)
    public static List<TemplateDocumento__c> getTemplates(String oppId) {
        Opportunity opp = OpportunityDA.getById(oppId);
        if (opp == null) throw new IllegalArgumentException('Oportunidade não encontrado com esse ID');
        List<TemplateDocumento__c> templates = TemplateSelector.getTemplatesByEmpId(opp.Empreendimento__c);
        
        return templates;
    }
    
}